insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "id_lista1", "idLista1", "Id Lista1", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "titlu_articol", "titluArticol", "Titlu Articol", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "denumirea_revistei", "denumireaRevistei", "Denumirea Revistei", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "vol", "vol", "Vol", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "nr", "nr", "Nr", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "pagina_de_inceput", "paginaDeInceput", "Pagina De Inceput", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "pagina_de_sfarsit", "paginaDeSfarsit", "Pagina De Sfarsit", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "factor_impact", "factorImpact", "Factor Impact", "double");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "id_lista2", "idLista2", "Id Lista2", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "titlu_articol", "titluArticol", "Titlu Articol", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "denumirea_revistei", "denumireaRevistei", "Denumirea Revistei", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "vol", "vol", "Vol", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "nr", "nr", "Nr", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "pagina_de_inceput", "paginaDeInceput", "Pagina De Inceput", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "pagina_de_sfarsit", "paginaDeSfarsit", "Pagina De Sfarsit", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "id_lista3", "idLista3", "Id Lista3", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "titlu_articol", "titluArticol", "Titlu Articol", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "denumirea_revistei", "denumireaRevistei", "Denumirea Revistei", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "vol", "vol", "Vol", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "nr", "nr", "Nr", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "pagina_de_inceput", "paginaDeInceput", "Pagina De Inceput", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "pagina_de_sfarsit", "paginaDeSfarsit", "Pagina De Sfarsit", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "id_lista4", "idLista4", "Id Lista4", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "titlu_articol", "titluArticol", "Titlu Articol", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "denumirea_volumului", "denumireaVolumului", "Denumirea Volumului", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "denumirea_conferintei", "denumireaConferintei", "Denumirea Conferintei", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "locul_desfasurarii", "loculDesfasurarii", "Locul Desfasurarii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "data_desfasurarii", "dataDesfasurarii", "Data Desfasurarii", "date");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "pagina_de_inceput", "paginaDeInceput", "Pagina De Inceput", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "pagina_de_sfarsit", "paginaDeSfarsit", "Pagina De Sfarsit", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "id_lista5", "idLista5", "Id Lista5", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "titlu_conferinta", "titluConferinta", "Titlu Conferinta", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "denumirea_volumului", "denumireaVolumului", "Denumirea Volumului", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "denumirea_manifestarii", "denumireaManifestarii", "Denumirea Manifestarii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "locul_desfasurarii", "loculDesfasurarii", "Locul Desfasurarii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "data_desfasurarii", "dataDesfasurarii", "Data Desfasurarii", "date");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "pagina_de_inceput", "paginaDeInceput", "Pagina De Inceput", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "pagina_de_sfarsit", "paginaDeSfarsit", "Pagina De Sfarsit", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "id_lista6", "idLista6", "Id Lista6", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "titlu_monografie", "titluMonografie", "Titlu Monografie", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "editura", "editura", "Editura", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "localitatea", "localitatea", "Localitatea", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "anul_aparitiei", "anulAparitiei", "Anul Aparitiei", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "numar_pagini", "numarPagini", "Numar Pagini", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "id_lista7", "idLista7", "Id Lista7", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "titlu", "titlu", "Titlu", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "editura", "editura", "Editura", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "localitatea", "localitatea", "Localitatea", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "anul_aparitiei", "anulAparitiei", "Anul Aparitiei", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "numar_pagini", "numarPagini", "Numar Pagini", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "id_lista8", "idLista8", "Id Lista8", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "autorul_care_citeaza", "autorulCareCiteaza", "Autorul Care Citeaza", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "denumirea_revistei", "denumireaRevistei", "Denumirea Revistei", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "vol", "vol", "Vol", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "numar_pagini", "numarPagini", "Numar Pagini", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "id_lista9", "idLista9", "Id Lista9", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "titlu_articol", "titluArticol", "Titlu Articol", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "autorii", "autorii", "Autorii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "denumirea_volumului", "denumireaVolumului", "Denumirea Volumului", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "denumirea_conferintei", "denumireaConferintei", "Denumirea Conferintei", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "locul_desfasurarii", "loculDesfasurarii", "Locul Desfasurarii", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "data_desfasurarii", "dataDesfasurarii", "Data Desfasurarii", "date");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "pagina_de_inceput", "paginaDeInceput", "Pagina De Inceput", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "pagina_de_sfarsit", "paginaDeSfarsit", "Pagina De Sfarsit", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "anul", "anul", "Anul", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista10", "id_lista10", "idLista10", "Id Lista10", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista10", "tip_grant", "tipGrant", "Tip Grant", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista10", "perioada", "perioada", "Perioada", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista10", "suma", "suma", "Suma", "double");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista10", "director_program", "directorProgram", "Director Program", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista1", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista1", "id_lista1", "idLista1", "Id Lista1", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista2", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista2", "id_lista2", "idLista2", "Id Lista2", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista3", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista3", "id_lista3", "idLista3", "Id Lista3", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista4", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista4", "id_lista4", "idLista4", "Id Lista4", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista5", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista5", "id_lista5", "idLista5", "Id Lista5", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista6", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista6", "id_lista6", "idLista6", "Id Lista6", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista7", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista7", "id_lista7", "idLista7", "Id Lista7", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista8", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista8", "id_lista8", "idLista8", "Id Lista8", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista9", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista9", "id_lista9", "idLista9", "Id Lista9", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista10", "user_id", "userId", "User Id", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("useri_lista10", "id_lista10", "idLista10", "Id Lista10", "bigint");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "user_id", "userId", "User Id", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "email_address", "emailAddress", "Email Address", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "password", "password", "Password", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "user_right", "userRight", "User Right", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "user_status", "userStatus", "User Status", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "first_name", "firstName", "First Name", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "last_name", "lastName", "Last Name", "varchar");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "birth_date", "birthDate", "Birth Date", "date");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "functie_didactica", "functieDidactica", "Functie Didactica", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "doctor", "doctor", "Doctor", "bit");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "doctor_din", "doctorDin", "Doctor Din", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "conducator_doctorat", "conducatorDoctorat", "Conducator Doctorat", "bit");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "doctoranzi_stagiu_zi", "doctoranziStagiuZi", "Doctoranzi Stagiu Zi", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "doctoranzi_stagiu_fr", "doctoranziStagiuFr", "Doctoranzi Stagiu Fr", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "level", "level", "Level", "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("users", "consultant", "consultant", "Consultant", "bit");


insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista1", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista2", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista3", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista4", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista5", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista6", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista7", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista8", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista9", "id_user", "IDUser", null, "int");
insert into metatable (nume_tabela, camp_tabela, camp_obiect, camp_vizual, tip) values ("lista10", "id_user", "IDUser", null, "int");
